### ISSUE TITLE
Unexpected string error

### ISSUE THREAD

**Issue by mutlupide** [cooolbros/hud-merger#10]
Merging ammo, health and time panel gives this error. Tried rayshud and FlawHUD and they gave this error too. Some other options give this error too but idk what they are i just tried choosing every option and gave 2 unexpected string error.

![Ekran Görüntüsü (4)](https://github.com/user-attachments/assets/3373c26a-e239-458a-b5eb-cc36cf85a760)

**Comment by russandro** [comment]
It happened to me too, a while ago.
Check my once opened issue about it.

**Comment by cooolbros** [comment]
Hi thanks for reporting this issue, I think its not related to #9 because that is a .res file error and this is a HUD Animations error.

Unfortunately I'm not able to replicate this in the latest main branch or version 2.0.2 release, if possible could you provide a more detailed replication?

**Comment by mutlupide** [comment]
> Hi thanks for reporting this issue, I think its not related to #9 because that is a .res file error and this is a HUD Animations error.
> 
> Unfortunately I'm not able to replicate this in the latest main branch or version 2.0.2 release, if possible could you provide a more detailed replication?

I'm copying PeachHud files to a empty folder. While other elements work, the things that need hudanimations file gives that error. I tried ammo, health and time panel and status element and all of them gave that error. Tried on 2.0.2. Other huds give this error too.

**Comment by cooolbros** [comment]
I tried reproducing the error by merging Health, Ammo and Time Panel, then everything from PeachHUD and budhud, but still can't get the HUD animations syntax error.

The HUDAnimationsSerializerTests.DeserializeTest test also passes for PeachHUD, budhud, flawhud and rayshud.

Ive released a new prelease version with the latest main branch code, can you try with version 2.0.3 prerelease? 

https://github.com/cooolbros/hud-merger/releases/tag/2.0.3

**Comment by mutlupide** [comment]
> I tried reproducing the error by merging Health, Ammo and Time Panel, then everything from PeachHUD and budhud, but still can't get the HUD animations syntax error.
> 
> The HUDAnimationsSerializerTests.DeserializeTest test also passes for PeachHUD, budhud, flawhud and rayshud.
> 
> Ive released a new prelease version with the latest main branch code, can you try with version 2.0.3 prerelease?
> 
> https://github.com/cooolbros/hud-merger/releases/tag/2.0.3

Now it gives this error. I tried reinstalling the game before on 2.0.2 and didn't work. (That "hud" folder is empty. I'm not sure if this error comes because of that file is empty but other elements work.)
![resim](https://github.com/user-attachments/assets/d6eac99c-88e8-4e13-a176-0652d86c8d41)

**Comment by cooolbros** [comment]
Nevermind, this was another language error similar to #5

The HUD Animations parser called `.ToLower` on the animation command to do a case insensitive comparison, but in Turkish the capital `I` is converted to a dotless i (`ı`), causing the unexpected `SetınputEnabled` error, which is also why again I couldn't reproduce it.

I've fixed the parser by using `.ToLowerInvariant` which does a cultureless conversion and also added tests to ensure all serialized HUD animations are also deserializeable in every culture, just in case there are inconsistencies in culture serialization.

**Comment by cooolbros** [comment]
I've released the fix in [release version 2.0.4](https://github.com/cooolbros/hud-merger/releases/tag/2.0.4), can you try it with the new version?

**Comment by mutlupide** [comment]
> I've released the fix in [release version 2.0.4](https://github.com/cooolbros/hud-merger/releases/tag/2.0.4), can you try it with the new version?

Alright it's fixed thanks!
