### ISSUE TITLE
Errors with .net even though I have 5.0 installed

### ISSUE THREAD

**Issue by Blu-Team** [cooolbros/hud-merger#2]
I'm a little confused as to why this is happening. First, it didn't open the link. I went into the github and found the download link. I downloaded it for windows x64, as that is my os, but it said I already had it installed. I tried the repair option and that completed succefully, but it still doesn't work. Why would this be? (I also tried the most recent version aka from code but I don't know how to build it.)

![image](https://github.com/cooolbros/hud-merger/assets/132679275/f4b6a9c6-a8af-4693-9f8d-a7b9abd180d4)

**Comment by epicrockhopper** [comment]
I believe you have to install EXCACTLY 5.0. Installing the latest version doesn't count

**Comment by Blu-Team** [comment]
> I believe you have to install EXCACTLY 5.0. Installing the latest version doesn't count

Ah alright, I'll try that later today and edit this comment if it worked or not.

**Comment by cooolbros** [comment]
I've released a new version of the HUD Merger that upgrades to the latest .NET, can you download the new HUD Merger version and see if this issue persists? You will need the .NET 8 runtime for desktop apps: https://dotnet.microsoft.com/download/dotnet/8.0/runtime

**Comment by Blu-Team** [comment]
> I've released a new version of the HUD Merger that upgrades to the latest .NET, can you download the new HUD Merger version and see if this issue persists? You will need the .NET 8 runtime for desktop apps: https://dotnet.microsoft.com/download/dotnet/8.0/runtime

I completely forgot to say that epicrockhopper's solution fixed it. And thanks! I'll download this one if I need to do use HUD Merger again.

**Comment by cooolbros** [comment]
Thats good to hear, glad it worked
