### ISSUE TITLE
"hudanimation_manifest" was not present in the dictionary.

### ISSUE THREAD

**Issue by ChickenBurgah** [cooolbros/hud-merger#3]
When i tried to merge my huds I get this error, I try with a few things and this error only happens when I try to modify the life and ammo of the hud.
![imagen_2023-11-25_002521512](https://github.com/cooolbros/hud-merger/assets/151981895/2b4c7724-466c-4c41-af25-9325d9f507e6)

**Comment by cooolbros** [comment]
Fixed in c2690e9
