### ISSUE TITLE
Hud merging not working

### ISSUE THREAD

**Issue by NojusKojos** [cooolbros/hud-merger#4]
So I really like mkhud and lavahud, so I wanted to put lavahuds health and some other elements on to mkhud, the merging process seemed to be succesful, but when I launched TF2 everything was lava hud, I didn't even think there was a single element of mkhud left lol. I've tried to merge with other huds aswell, but everytime one hud seemed to overtake the other one. I don't know if i put on too many elements from lava hud onto mkhud but I didn't put every single one on lol.

**Comment by cooolbros** [comment]
Closing because the issue was a user error:

![image](https://github.com/cooolbros/hud-merger/assets/43595566/d84fc0b5-ab44-49d4-984e-504b142ee34a)
