### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by russandro** [cooolbros/hud-merger#9]
![image](https://github.com/user-attachments/assets/04e1ff2a-2d82-4119-bb16-ca4ab7abad3e)
This weird error pops up when I try to merge those two huds.
(I even looked at the code but it seems that there aren't any errors...)
_Screen below:_
![image](https://github.com/user-attachments/assets/31a7e4bb-c170-4a16-a043-567f53e2c9c8)

**Comment by cooolbros** [comment]
The HUD Merger is set to not allow multiple line strings, because it's usually a sign of a missing closing double quote, which if skipped optimistically could cause an incorrect parse.

As a workaround, you can remove the "command" section, run the merge, then add the section back in inside the result HUD.

**Comment by russandro** [comment]
Actually... to solve this.. at the time..
It happened that I just needed to invert the merging process so that it would work.
My fault for actually not updating the thread but yeah... basically I just inverted the process (merging RebelHud into BudHud) and that was enough.. I guess cuz the richer hud in terms of changes & files was BudHud, so for the program it was easier to port those few little thing from Rebel into Bud.

~~Even tho yeah you right, maybe that could've worked too.~~

**Comment by russandro** [comment]
(Just realized it was the author replying.. at the time I didn't actually read that so in detail 😅)
Assume it worked (my method) cuz doing the opposite (inverting which hud change which) the program managed to not edit that particular file then..
